### ISSUE TITLE
Extended Reality (XR) Fundamentals

### ISSUE THREAD

**Issue by Domenic-MZS** [Domenic-MZS/Essential-ARscape#6]
**Is your feature request related to a problem? Please describe.**
This issue aims to add base documentation files for Extended Reality (XR) fundamental areas, background and concepts.

**Describe the Solution You'd Like**
 - [x] Definition of Extended Reality (XR)
 - [x] Extended Reality Areas
 - [x] Understanding User Interaction
 - [x] Importance of Extended Reality (XR) and it's current state of development in the market
 - [x] Extended Reality Programs and background

**Additional Context**
 - #3

**Comment by Domenic-MZS** [comment]
Maybe it's a good idea to add some [accessibility][access] topics.

[access]: https://xraccess.org/
